### ISSUE TITLE
Add JDM link

### ISSUE THREAD

**Issue by shuvashish76** [MuntashirAkon/DeleteYourAccountFromWebsite#2]
We've a project called [JDM](https://github.com/jdm-contrib/jdm) with MIT license.
https://justdeleteme.xyz/
Since the whole purpose of this project is to help others (possibly created for your own use) I'd like to suggest: add the above link in readme for those who are searching for similar project as it supports more sites with lot more infos, updated more frequently and it has browser extension support.
Thanks

**Comment by MuntashirAkon** [comment]
Please create a PR with the link on top of README. I shall archive the project afterwards.
